//wishlist 상수 데이터로 랜더링하기
export const itemList = [
  {
    id: 1,
    item_name: "캐멋진 살로몬",
    item_price: 234000,
    category: "cool",
    img: "cool1.png",
  },
  {
    id: 2,
    item_name: "짱멋진 눕시",
    item_price: 345938,
    category: "cool",
    img: "cool2.png",
  },
  {
    id: 3,
    item_name: "사고싶어 맥스",
    item_price: 768049,
    category: "cool",
    img: "cool3.png",
  },
  {
    id: 4,
    item_name: "사주세요 칼하트",
    item_price: 78000,
    category: "cool",
    img: "cool4.png",
  },
  {
    id: 5,
    item_name: "내게와 lp",
    item_price: 188000,
    category: "cool",
    img: "cool5.png",
  },
  {
    id: 6,
    item_name: "내꺼예요 된장포스",
    item_price: 208000,
    category: "cool",
    img: "cool6.png",
  },
  {
    id: 7,
    item_name: "샀어요 스투시",
    item_price: 100000,
    category: "cool",
    img: "cool7.png",
  },
  {
    id: 8,
    item_name: "내놔 식기 세트",
    item_price: 24800,
    category: "cute",
    img: "cute1.png",
  },
  {
    id: 9,
    item_name: "그로밋 머그컵",
    item_price: 25000,
    category: "cute",
    img: "cute2.png",
  },
  {
    id: 10,
    item_name: "귀엽지요? 앵브록스",
    item_price: 35000,
    category: "cute",
    img: "cute3.png",
  },
  {
    id: 11,
    item_name: "이우가마카라스",
    item_price: 188000,
    category: "cute",
    img: "cute4.png",
  },
  {
    id: 12,
    item_name: "사실 그냥 그런 접시",
    item_price: 25000,
    category: "cute",
    img: "cute5.png",
  },
  {
    id: 13,
    item_name: "깜찍한 keen",
    item_price: 136000,
    category: "cute",
    img: "cute6.png",
  },
  {
    id: 14,
    item_name: "디지털 카메라",
    item_price: 225000,
    category: "cute",
    img: "cute7.png",
  },
  {
    id: 15,
    item_name: "사주나? 쏜희 키링",
    item_price: 1300000,
    category: "trash",
    img: "trash1.png",
  },
  {
    id: 16,
    item_name: "바르셀로나 14-15",
    item_price: 500000,
    category: "trash",
    img: "trash2.png",
  },
  {
    id: 17,
    item_name: "간절한 유럽행 티켓",
    item_price: 2500000,
    category: "trash",
    img: "trash3.png",
  },
  {
    id: 18,
    item_name: "나도 이펙터",
    item_price: 300000,
    category: "trash",
    img: "trash4.png",
  },
];
